#!/usr/bin/env python3
"""counterproof.py [PAGE] -- for every scenario, each of its breaks: one small change in a scratch copy of the page
(default: the template, ../template/book.html), the scenario run alone, and it must print FAIL naming the field the
break is about. Every scenario must also be ok on the unbroken page first. Runs JOBS (default 6) at a time, all on one
Chrome pool (lib/pool.py, JOBS headless Chromes) started here and closed at the end, whatever happens.
Writes COUNTERPROOF.md next to run_all.sh and deletes every scratch copy afterwards. Never touches the page itself.
A break whose text is not found exactly once in the page (the page moved on) counts as NOT PROVEN: rewrite it."""
import os, re, shutil, subprocess, sys, tempfile, time
from concurrent.futures import ThreadPoolExecutor
here = os.path.dirname(os.path.abspath(__file__)); suite = os.path.dirname(here)
src_p = sys.argv[1] if len(sys.argv) > 1 else os.path.join(suite, '..', 'template', 'book.html')
base = open(src_p, encoding='utf-8').read()
ver = re.search(r'PAGE_VERSION="([^"]*)"', base).group(1)
class Stale(Exception): pass
def once(page, old, new):
    n = page.count(old)
    if n != 1: raise Stale('break text found %d times, not once' % n)
    return page.replace(old, new)
# scenario, what the break does, old text, new text, field expected in the FAIL line
B = [
 ('ab_counts', 'the count of "Erledigt" adds the archive again', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length;', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length+archCount("erledigt");', 'erledigtBefore'),
 ('ab_counts', 'before loading, the summaries in "statistik" are not read', 'function statArch(k){let n=0;', 'function statArch(k){return 0;let n=0;', 'archivBefore'),
 ('ab_counts', 'once the archive is loaded, "Erledigt" counts its cards too', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length;', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length+(arch?archOnly().length:0);', 'erledigtAfter'),
 ('ab_counts', 'the line under "Erledigt" names the archived cards again', 'const inArch=0,archLine', 'const inArch=archCount("erledigt"),archLine', 'erlLine'),
 ('ab_counts', '"Tokens (Karten)" counts the cards in the book only', 'function tokensOf(v){let sum=0;for(const r of allCards()){', 'function tokensOf(v){let sum=0;for(const r of rows){', 'tokensB27'),
 ('ab_counts', '"Empfehlung getroffen" counts the cards in the book only', 'function recHit(v){let n=0,m=0;for(const r of allCards()){', 'function recHit(v){let n=0,m=0;for(const r of rows){', 'recB27'),
 ('ab_counts', '"Statistik" does not load the archive', '  loadArchive();if(archLoading)w.append(', '  if(archLoading)w.append(', 'getsStat'),
 ('ab_counts', 'the book count leaves the archive docs out', 'return rows.length+gsp.length+auftraege.length+stat.length+archDocs()+', 'return rows.length+gsp.length+auftraege.length+stat.length+', 'bookBefore'),
 ('ab_filter', 'the search in "Archiv" finds every card', 'const hits=cards.filter(r=>bpass(r)&&(!t||abHay(r).includes(t)));', 'const hits=cards.filter(r=>bpass(r));', 'searchRows'),
 ('ab_filter', 'the filters in "Archiv" hide nothing', 'const hits=cards.filter(r=>bpass(r)&&(!t||abHay(r).includes(t)));', 'const hits=cards.filter(r=>!t||abHay(r).includes(t));', 'filterRows'),
 ('ab_filter', '"≠" filters like "="', 'return f.op==="="?hit:!hit});\n  const fOn=!!(bFilt', 'return hit});\n  const fOn=!!(bFilt', 'filterNeRows'),
 ('ab_filter', 'a release with hits stays shut while searching', 'const shut=hunt?false:!abRel.has(z)', 'const shut=!abRel.has(z)', 'searchGroups'),
 ('ab_filter', 'the orders are not searched', 'const orders=archOf("auftraege").filter(a=>!t||abHay(a).includes(t))', 'const orders=archOf("auftraege").filter(a=>!t)', 'orderHit'),
 ('ab_filter', 'a card number from the archive is looked for in the book only', '  if(!r&&archOnly().some(x=>x.nr===nr))return openArchived(nr,note);\n', '', 'orderToCard'),
 ('ab_phone', 'the filter bar of "Archiv" is 480 px wide', '.abfil{display:flex}', '.abfil{display:flex;min-width:480px}', 'overflowing'),
 ('ab_phone', 'a long word in an archived order does not wrap', '.abtab2 td.t{overflow-wrap:anywhere}', '.abtab2 td.t{white-space:nowrap}', 'overflowing'),
 ('ab_phone', 'the "Archiv" mark is 420 px wide', '.archmark{font-size:11px;', '.archmark{display:inline-block;min-width:420px;font-size:11px;', 'overflowing'),
 ('ab_releases', 'a closed release is still listed', 'function relClosed(z){if(!z||z===relZ())return false;', 'function relClosed(z){return false;', 'groups'),
 ('ab_releases', 'the current release goes once it is published', 'if(cur)zs.push(cur);', 'if(cur&&!(stat.find(x=>x.version===cur)||{}).veroeffentlicht)zs.push(cur);', 'groups'),
 ('ab_releases', 'a rejected card holds its release open', '&&r.blatt!=="erledigt"&&r.blatt!=="verworfen")}', '&&r.blatt!=="erledigt")}', 'groups'),
 ('ab_releases', 'a release without "veroeffentlicht" counts as closed', 'return !!(s&&s.veroeffentlicht)&&', 'return !!s&&', 'groups'),
 ('ab_releases', 'an open card does not hold its release', '&&!rows.some(r=>String(r.ziel||"").trim()===z&&', '&&!rows.some(r=>false&&', 'groups'),
 ('ab_releases', 'the next release comes back although it is closed', 'if(nx&&!relClosed(nx))ahead.add(nx);', 'if(nx)ahead.add(nx);', 'groups'),
 ('ab_releases', 'no hint line', 'el("p",{class:"hint",id:"rel-closed",text:"Abgeschlossene Releases: Summen unter Statistik, Karten im Archiv"})', '""', 'hint'),
 ('ab_restore', '"Zurückholen" writes at the first tap', 'else{b.onclick=()=>{abSure.add(r.nr);render(true)};bar.append(b)}', 'else{b.onclick=()=>archRestore(r,b,note);bar.append(b)}', 'writesAfterFirst'),
 ('ab_restore', '"Zurückholen" asks with a browser dialog', 'else{b.onclick=()=>{abSure.add(r.nr);render(true)};bar.append(b)}', 'else{b.onclick=()=>{if(confirm("Zurückholen?"))archRestore(r,b,note)};bar.append(b)}', 'dialogs'),
 ('ab_restore', 'only some fields come back', 'const body=Object.assign({},e);delete body.id;', 'const body={ueberschrift:e.ueberschrift,blatt:e.blatt,ziel:e.ziel};', 'sameFields'),
 ('ab_restore', 'the entry\'s "id" is written into the card', 'const body=Object.assign({},e);delete body.id;', 'const body=Object.assign({},e);', 'hasId'),
 ('ab_restore', 'the card stays in the archive doc', 'try{await db.doc("archiv/"+aid).update({eintraege:rest});', 'try{', 'archLeft'),
 ('ab_restore', 'the summary in "statistik" is not lowered', 'try{await db.doc("statistik/"+sd.id).update({archiv:na});sd.archiv=na}catch(x){}', '', 'statArchiv'),
 ('ab_restore', 'the page says nothing when it is done', 'abNote=el("span",{},msg+" ",go);', '', 'msg'),
 ('ab_restore', 'a card number already in the book is written over', 'if(cur.exists)return stop(', 'if(false)return stop(', 'clash'),
 ('ab_restore', 'a card brought back keeps its old release as target', '{const nz=restoreZiel(body.ziel);if(nz.vorher!=null){body.ziel_vorher=nz.vorher;body.ziel=nz.ziel}}', '', 'ziel'),
 ('ab_restore', 'the old target is not kept in ziel_vorher', 'body.ziel_vorher=nz.vorher;body.ziel=nz.ziel', 'body.ziel=nz.ziel', 'zielVorher'),
 ('ab_restore', 'the question does not name the new target', '(nz.vorher!=null?", Ziel wird "+nz.ziel+" (vorher "+(nz.vorher||"offen")+")":" ("+(r.ziel||"Ziel offen")+")")', '" ("+(r.ziel||"Ziel offen")+")"', 'askText'),
 ('ab_restore', '"Erledigt" counts the loaded archive too', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length;', 'rows.filter(r=>visible(r)&&r.blatt==="erledigt").length+(arch?archOnly().filter(r=>r.blatt==="erledigt").length:0);', 'countBefore'),
 ('ab_restore_keep', 'without a current release the target is emptied', 'return cur&&cur!==o?{ziel:cur,vorher:o}', 'return cur!==o?{ziel:cur,vorher:o}', 'ziel'),
 ('ab_restore_keep', 'ziel_vorher is written when nothing changes', '{const nz=restoreZiel(body.ziel);if(nz.vorher!=null){body.ziel_vorher=nz.vorher;body.ziel=nz.ziel}}', '{const nz=restoreZiel(body.ziel);body.ziel_vorher=nz.vorher!=null?nz.vorher:body.ziel;body.ziel=nz.ziel}', 'hasVorher'),
 ('ab_restore_ro', '"Zurückholen" is offered without write access', 'if(db&&canWrite){const sure=abSure.has(r.nr);', 'if(db){const sure=abSure.has(r.nr);', 'restoreBtns'),
 ('ab_search', 'the card search leaves the archive out', '  loadArchive();const pool=rows.concat(archOnly());', '  const pool=rows;', 'hits'),
 ('ab_search', 'an archived hit is not marked "Archiv"', 'inA?el("span",{class:"archmark",text:"Archiv"}):""', '""', 'hits'),
 ('ab_search', 'a number search leaves the archive out', 'hits=pool.filter(r=>{const k=', 'hits=rows.filter(r=>{const k=', 'numHits'),
 ('ab_search', 'every keystroke reads the archive again', 'if(arch||archLoading||archFail||!db)return archLoading;', 'if(archLoading||!db)return archLoading;', 'getsSearch'),
 ('ab_search', '"Öffnen" on an archived hit stays in the view it was in', 'view="ablage";focusNr=nr;foundNr=null;', 'focusNr=nr;foundNr=null;', 'openView'),
 ('ab_search', 'the release of the found card stays shut', 'abFlip(r._rel,true);abOpen.add(nr);render(true);', 'abOpen.add(nr);render(true);', 'groupOpen'),
 ('ab_stat_cols', 'there is no tab "Karten und Tokens"', '["karten","Karten und Tokens"],', '', 'subTab'),
 ('ab_stat_cols', 'an Art the page does not know gets no column', '...ARTS.map(a=>a[0]),...KL.flatMap(r=>Object.keys(byArt(r)))', '...ARTS.map(a=>a[0])', 'heads'),
 ('ab_stat_cols', 'a missing value reads 0 instead of "–"', 'return v==null?"–":(fmt||fmtN)(v)},r=>num(f(r))];', 'return (fmt||fmtN)(v==null?0:v)},r=>num(f(r))];', 'rowB26'),
 ('ab_stat_cols', 'the difference has no sign', 'K("Differenz",r=>r.tokens_diff,sg)', 'K("Differenz",r=>r.tokens_diff,tk)', 'rowB27'),
 ('ab_stat_cols', 'a value that is no number is shown as it comes', 'const num=x=>x==null||x===""||typeof x==="boolean"||!isFinite(Number(x))?null:Number(x)', 'const num=x=>x==null||x===""?null:Number(x)', 'rowB25'),
 ('ab_tab', 'the archive is read at start, with the cards', 'liveAt=Date.now();liveLine();', 'liveAt=Date.now();liveLine();loadArchive();', 'getsAtStart'),
 ('ab_tab', 'the archive is subscribed instead of read once', 'archLoading=db.collection("archiv").get().then(', 'archLoading=new Promise(ok=>db.collection("archiv").onSnapshot(ok)).then(', 'subsEnd'),
 ('ab_tab', 'the archive is read again every time the tab opens', 'b.onclick=()=>{view=k;focusNr=null;const ks=', 'b.onclick=()=>{view=k;focusNr=null;if(k==="ablage")arch=null;const ks=', 'getsAfterReopen'),
 ('ab_tab', '"Archiv" stands before "Erledigt"', '["archiv","Erledigt",null],["ablage","Archiv",null],', '["ablage","Archiv",null],["archiv","Erledigt",null],', 'tabs'),
 ('ab_tab', 'the releases start open', 'const shut=hunt?false:!abRel.has(z)', 'const shut=false', 'groups'),
 ('ab_tab', 'the table has other columns than "Erledigt"', 'const COLS_A=xCols(),dir=', 'const COLS_A=xCols().slice(0,4),dir=', 'heads'),
 ('ab_tab', 'an archived card keeps its answer field and its dropdowns', 'for(const x of d.querySelectorAll(".answer,.fields"))x.remove();', '', 'readOnly'),
 ('ab_tab', 'the orders and talks start open', 'gshut=t?false:!abRel.has(gk)', 'gshut=false', 'subgroups'),
 ('ab_tab', 'an open group is not kept for the session', 'try{sessionStorage.setItem("eb-abrel",JSON.stringify([...abRel]))}catch(e){}', '', 'storedOpen'),
 ('ab_tab', 'an archived talk opens with its answer field', 'el("td",{colspan:"3"},gFull(h(x)))', 'el("td",{colspan:"3"},x.nachrichten?gItem(x,true):gFull(h(x)))', 'talkInputs'),
 ('archive_debounce', 'the archive is drawn again on every keystroke', 's.addEventListener("input",()=>{q=s.value;clearTimeout(qTimer);qTimer=setTimeout(()=>{const o=$("#suche"),pos=o?o.selectionStart:null;render();const n=$("#suche");if(n&&o===document.activeElement){n.focus();try{if(pos!=null)n.setSelectionRange(pos,pos)}catch(e){}}},200)});', 's.addEventListener("input",()=>{q=s.value;const pos=s.selectionStart;render();const n=$("#suche");if(n){n.focus();try{n.setSelectionRange(pos,pos)}catch(e){}}});', 'redrawsWhileTyping'),
 ('archive_filter', 'the "Ziel" and "von" filters let every card through', 'const pass=r=>["ziel","von"].every(', 'const pass=r=>true||["ziel","von"].every(', 'zielOnly'),
 ('archive_filter_phone', 'on a phone the filters stay in the hidden columns', '@media (max-width:640px){.atab tr.frow{display:none}.afil{display:flex}', '@media (max-width:1px){.atab tr.frow{display:none}.afil{display:flex}', 'rowFiltersShown'),
 ('archive_sort', 'a click on a row of "Erledigt" jumps to the card on its own page again', 'tr=xRow(r,open,axOpen);', 'tr=xRow(r,open,axOpen);tr.addEventListener("click",e=>{e.stopImmediatePropagation();gotoCard(r.nr)},true);', 'openedBelow'),
 ('art_field', 'Art reads "art" only (old typ "Auftrag"/"Aufgabe" become Entscheidung)', 'return t==="Auftrag"?"auftrag":t==="Aufgabe"?"aufgabe":"entscheidung"}', 'return "entscheidung"}', 'arts'),
 ('art_field', '"typ" wins over "art"', 'function artOf(r){const a=', 'function artOf(r){if(r&&r.typ==="Aufgabe")return "aufgabe";const a=', 'arts'),
 ('art_field', 'writing Art writes "typ" too', 'if(s.value!==l){l=s.value;save(r,{[field]:s.value},note)}', 'if(s.value!==l){l=s.value;save(r,{[field]:s.value,typ:s.value},note)}', 'write'),
 ('art_field', 'the "Hinweise & Aufgaben" column keys on the raw "art" again', 'function isArt(r){const a=artOf(r);return', 'function isArt(r){const a=r.art;return', 'cols'),
 ('backup_pictures', 'the picture files are not saved along', 'let miss=0;out.bilder={};for(const d of Object.values(out.daten.auftragsbilder)){', 'let miss=0;out.bilder={};for(const d of []){', 'bilder'),
 ('backup_pictures', 'the archive is not saved', '"gespraech","statistik","meta","archiv"]){', '"gespraech","statistik","meta"]){', 'archiv'),
 ('backup_pictures', 'a picture that could not be read is not counted', 'note.textContent="gesichert"+(miss?', 'note.textContent="gesichert"+(false?', 'note'),
 ('backup_pictures', 'the file is not base64', 'data:bytesB64(u)}', 'data:String(u)}', 'aaa'),
 ('book_count', 'pictures are left out of the document count', '+[...metaHave.values()].filter(Boolean).length+img.size}', '+[...metaHave.values()].filter(Boolean).length}', 'count'),
 ('book_full', 'a full book says "bitte noch einmal" like any failure', 'function failText(e,t){if(!(e&&e.code==="quota_exceeded"))return t;', 'function failText(e,t){return t;', 'orderNote'),
 ('book_warn', 'the warning starts only at 40000 documents', 'BOOK_WARN=4000', 'BOOK_WARN=40000', 'statsWarn'),
 ('card_back', 'a card handed back with a new message keeps its remembered closed state', 'if(nz&&kSeen[r.nr]!==nz&&!(ts(nz)<=oa)){', 'if(false){', 'toPruefen'),
 ('card_back_existing', 'v101\'s seed "eb-kseen" is honoured again, so existing "Prüfen" cards stay shut', 'localStorage.getItem("eb-kopen")', 'localStorage.getItem("eb-kseen")', 'newerMessage'),
 ('card_comment_first', 'the picture is stored before the comment goes to Claude', '    let live=false,why="";\n    if(t||imgs){const L=await liveSend(', '    if(imgs)await storeImages(fk);let live=false,why="";\n    if(t||imgs){const L=await liveSend(', 'order'),
 ('card_double', 'a second tap sends while the first is still sending', 'const sendCard=async(patch)=>{if(sending)return false;', 'const sendCard=async(patch)=>{', 'sends'),
 ('card_image', 'the send button is not woken when a pasted image lands in the draft', 'ta.addEventListener("imgs",ck);', '', 'pasteEnabled'),
 ('card_pct', 'Claude\'s "fertig_pct" is ignored (the Stand alone decides)', 'function fertigPct(r){const v=pctOf(r.fertig_pct);if(v!=null)return v;', 'function fertigPct(r){', 'pct'),
 ('card_pct', '"Prüfen" and "Erledigt" without a value read "–" instead of 100', 'const b=r.blatt;return b==="erledigt"||b==="pruefen"?100:', 'const b=r.blatt;return b==="erledigt"||b==="pruefen"?null:', 'pct'),
 ('card_pct', '"Offen", "Entschieden" and "Vorrat" without a value read "–" instead of 0', 'b==="offen"||b==="entschieden"||b==="vorrat"?0:null}', 'b==="offen"||b==="entschieden"||b==="vorrat"?null:null}', 'pct'),
 ('card_pct', '"In Umsetzung" without a value reads 0 % instead of "–"', 'b==="offen"||b==="entschieden"||b==="vorrat"?0:null}', 'b==="offen"||b==="entschieden"||b==="vorrat"?0:0}', 'pct'),
 ('card_pct', 'the percentage follows the tokens instead of standing at the right end', '.pct{margin-left:auto;', '.pct{', 'rightGap'),
 ('card_pct', 'the percentage takes a line of its own on a wide card', '.pct{margin-left:auto;', '.pct{flex-basis:100%;text-align:right;margin-left:auto;', 'sameLineWide'),
 ('card_pct', 'the percentage is pale grey (below 4.5:1)', 'white-space:nowrap;font-family:var(--mono);font-size:12px;color:var(--muted)}', 'white-space:nowrap;font-family:var(--mono);font-size:12px;color:#c4c8d0}', 'minContrast'),
 ('card_pct', 'an order shows no percentage', 'li.append(note,pctSpan(orderPct(a)));return li;', 'li.append(note);return li;', 'orders'),
 ('card_pct_dark', 'the percentage is dark grey on the dark card', 'white-space:nowrap;font-family:var(--mono);font-size:12px;color:var(--muted)}', 'white-space:nowrap;font-family:var(--mono);font-size:12px;color:var(--muted)}@media (prefers-color-scheme:dark){.pct{color:#3a4150}}', 'minContrast'),
 ('card_pct_phone', 'the percentage is wider than the phone', '.pct{margin-left:auto;white-space:nowrap;', '.pct{margin-left:auto;white-space:nowrap;min-width:420px;', 'overflowing'),
 ('card_pct_phone', 'the percentage breaks over two lines', '.pct{margin-left:auto;white-space:nowrap;', '.pct{margin-left:auto;width:2em;', 'bad'),
 ('card_send', 'the card is not read again before the write (messages from the card as drawn)', 'let now=r.kommentare;try{const c=await db.doc("entscheidungen/"+r.nr).get();if(c.exists)now=(c.data()||{}).kommentare}catch(e){}', 'let now=r.kommentare;', 'kommentare'),
 ('dark_contrast', 'filled buttons are the light accent again in dark mode', '.bookfull{color:var(--wait)}', '.bookfull{color:var(--wait)}@media (prefers-color-scheme:dark){.act,.waitbadge{background:#4fb8ad!important}}', 'minContrast'),
 ('dark_mode', "the dark colours no longer answer the viewer's dark setting", '@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){', '@media (prefers-color-scheme:no-such){:root:not([data-theme="light"]){', 'bodyBackground'),
 ('deadline', 'a passed deadline still reads "Frist: …"', 'sum.append(t<=Date.now()?el("span",{class:"flag frist"', 'sum.append(false?el("span",{class:"flag frist"', 'past'),
 ('dep_chips', 'the other card does not say "blockiert"', '    for(const n of by)w.append(dep(n,"blockiert",false));\n', '', 'blocked702'),
 ('done_when', '"Fertig, wenn" no longer stands first under "Prüfen"', '  if(fwb&&r.blatt==="pruefen")b.append(fwb);\n', '', 'firstPruefen'),
 ('draft_files', 'a zip goes to the store and is not named in the note', 'if(!t)return x+" geht nicht: "+FT_NOTE;', '', 'zipNote'),
 ('draft_files', 'a sent file shows as a broken picture, not as a link', 'if(c&&typeof c.then!=="function"&&isFile(c))return fileChip(c);', '', 'sentLink'),
 ('draft_images', 'the × of a draft picture is white on white in dark mode again', '.thumbs .tw .tx{top:3px;right:3px;width:22px;height:22px;line-height:20px;font-size:15px;background:rgba(0,0,0,.72);color:#fff;', '.thumbs .tw .tx{top:3px;right:3px;width:22px;height:22px;line-height:20px;font-size:15px;background:#fff;', 'xContrast'),
 ('draft_images', 'a dropped file that is no picture is let through to the browser', 'e.preventDefault();e.stopPropagation();take(all)})}', 'if(!all.some(fRefuse)){e.preventDefault();e.stopPropagation()}take(all)})}', 'dropText'),
 ('earlier_search', 'the search in "Frühere" filters nothing', 'shown=hist.filter(h=>hay(h).includes(q))', 'shown=hist', 'rows'),
 ('earlier_table', 'a second click on a column head of "Frühere" does not turn the order round', 'b.addEventListener("click",()=>{if(gSort.k===k)gSort.down=!gSort.down;else gSort={k,down:true};', 'b.addEventListener("click",()=>{gSort={k,down:true};', 'reversed'),
 ('earlier_table_phone', '"Frühere" draws every row at once', 'for(const h of mine.slice(0,gMax)){const open=gOne===h.k;', 'for(const h of mine){const open=gOne===h.k;', 'drawn'),
 ('esc_overlays', 'the big picture listens for "Esc" instead of "Escape"', 'const esc=e=>{if(e.key==="Escape")close()}', 'const esc=e=>{if(e.key==="Esc")close()}', 'bigAfterEsc'),
 ('fields_phone', "the card's dropdowns get a minimum width of 420 px", '.verw{', '.fields select{min-width:420px}.verw{', 'bad'),
 ('fields_phone', 'the "Verworfen" group is 600 px wide', '.verw{margin:16px 0 0}', '.verw{margin:16px 0 0;min-width:600px}', 'overflowing'),
 ('focus_kept', 'a snapshot rebuilds the card the owner is typing in', 'if(dd&&!force&&!cardMoved(dd)&&(!pending||pending===dd.dataset.nr)){pending=dd.dataset.nr;renderReady();return}', '', 'sameNode'),
 ('focus_redraw', 'focus is not put back after a redraw', 'function focusBack(k){if(!k)return;', 'function focusBack(k){return;', 'viewButton'),
 ('header_times', '"Aufträge gelesen" ignores Claude\'s messages in talks', 'const tA=maxTs([c.auftraege_gelesen,...mine])', 'const tA=maxTs([c.auftraege_gelesen])', 'Aufträge gelesen'),
 ('imp_cancel', 'the question is a browser dialog', 'const sure=await new Promise(ok=>{impAsk=ok;yes.onclick=()=>ok(true);no.onclick=()=>ok(false)});', 'const sure=confirm("Vor dem Einlesen löschen?");', 'dialogs'),
 ('imp_cancel', '"Abbrechen" deletes and reads in anyway', 'no.onclick=()=>ok(false)', 'no.onclick=()=>ok(true)', 'writes'),
 ('imp_cancel', 'the question does not say what would be deleted', 'text:"Gelöscht werden: "+parts.join(", ")+".', 'text:"Gelöscht werden: alles.', 'what'),
 ('imp_cancel', 'the question counts only the cards', '"Im Buch stehen "+nHave+" Dokumente.', '"Im Buch stehen "+have.entscheidungen.length+" Dokumente.', 'question'),
 ('imp_empty', 'a book with only meta/statistik docs counts as not empty (it asks)', 'empty=IMP_MAIN.every(c=>!have[c].length)', 'empty=IMP_COLLS.every(c=>!have[c].length)', 'asked'),
 ('imp_empty', 'every write at once, no batches', 'IMP_BATCH=10,', 'IMP_BATCH=1000,', 'maxInFlight'),
 ('imp_empty', 'doc ids are not kept (new ids)', 'await db.doc(c+"/"+id).set(d);got[c]', 'await db.collection(c).add(d);got[c]', 'idsKept'),
 ('imp_empty', 'unknown collections are left out without a word', 'fremd=plan.fremd.length?', 'fremd=false?', 'note'),
 ('imp_empty', 'no progress while writing', 'n=>{const x=todo[Math.min(n,todo.length)-1];say("liest ein … "+n+" von "+todo.length+(x?" ("+x[0]+")":""))}', 'n=>{}', 'progress'),
 ('imp_empty', 'no count per collection at the end', 'const all=Object.keys(plan.daten[c]||{}).length;if(!all)continue;', 'const all=Object.keys(plan.daten[c]||{}).length;if(all)continue;', 'lines'),
 ('imp_empty', 'the cards are written before the pictures', 'const IMP_COLLS=["meta","statistik","auftragsbilder","entscheidungen",', 'const IMP_COLLS=["meta","statistik","entscheidungen","auftragsbilder",', 'order'),
 ('imp_from_helper', 'the pictures inside a file ("bilder") are ignored', 'if(b&&b.data)bilder[id]=', 'if(false)bilder[id]=', 'note'),
 ('imp_limit', 'no limit of 5000 documents', 'if(chk.n>BOOK_MAX)return say(', 'if(false)return say(', 'tooMany'),
 ('imp_limit', 'what stays in an empty book is not counted', 'if(chk.n+stay>BOOK_MAX)return say(', 'if(chk.n>BOOK_MAX)return say(', 'withBook'),
 ('imp_limit', 'a doc over 256 KB is not refused', 'if(b>DOC_MAX)bad.push(', 'if(false)bad.push(', 'tooBig'),
 ('imp_limit', 'an id with "/" is taken', 'if(!id||id.includes("/")||', 'if(!id||', 'badId'),
 ('imp_limit', 'a file without "daten" counts as a backup (an empty one)', 'throw "Die Datei ist keine Sicherung des Buchs (kein Feld „daten“).";', 'd.daten={};', 'noBackup'),
 ('imp_phone', 'the question box is 480 px wide', '.impask{border:1px solid', '.impask{min-width:480px;border:1px solid', 'overflowing'),
 ('imp_phone', '"Abbrechen" is smaller than 32 px on a phone', '.statbox .sub button,.vlog button{min-height:32px;min-width:32px}', '.statbox .sub button{min-height:32px;min-width:32px}', 'tall'),
 ('imp_pictures', 'an uploaded picture keeps pointing to its old asset', 'd=Object.assign({},d,{asset_id:u.id,url:"/_blob/"+u.id},', 'd=Object.assign({},d,{},', 'p2New'),
 ('imp_pictures', 'the assets still in the store are not asked for', 'for(const a of (l&&l.assets)||[])if(a&&a.id)inStore.add(a.id)', '', 'p4'),
 ('imp_pictures', 'a picture without a file is not left out', 'if(c==="auftragsbilder"&&d.asset_id&&!inStore.has(d.asset_id)&&!(assets&&plan.bilder[d.asset_id])){nofile++;continue}', '', 'folderNote'),
 ('imp_pictures', "the picture files in a folder's bilder/ are not read", 'if(dir==="bilder"){const m=', 'if(dir==="bilder_"){const m=', 'uploads'),
 ('imp_pictures', 'the base64 pictures in a file are not read', 'for(const [id,b] of Object.entries(d.bilder&&typeof d.bilder==="object"?d.bilder:{}))', 'for(const [id,b] of Object.entries({}))', 'q1New'),
 ('imp_pictures', 'pictures without a file are not counted', 'const pics=nofile?impN(nofile,"Bild","Bilder")+" ohne Datei":"";', 'const pics="";', 'folderNote'),
 ('imp_readonly', 'the buttons are on without write access', 'b.disabled=importing||!can()};arm();', 'b.disabled=importing};arm();', 'disabled'),
 ('imp_readonly', 'a file handed in reads in without write access', 'if(!files.length||importing||!can())return;', 'if(!files.length||importing)return;', 'asked'),
 ('imp_readonly', 'no word why the buttons are off', 'else if(!canWrite)note.textContent="Einlesen braucht Schreibrechte im Buch.";', 'else if(!canWrite)note.textContent="";', 'note'),
 ('imp_reopen', 'the open question is not ended when the settings are opened again', 'if(impAsk){impAsk(false);impAsk=null}', '', 'enabled'),
 ('imp_reopen', 'the end of an import reaches only the dialog it began in', 'for(const b of [here("import-datei-btn",bF),here("import-ordner-btn",bD)])', 'for(const b of [bF,bD])', 'enabled'),
 ('imp_reopen', 'the words of an import go to the closed dialog', 'say=t=>{here("import-stand",note).textContent=t}', 'say=t=>{note.textContent=t}', 'note'),
 ('imp_replace', '"Löschen und einlesen" deletes nothing', 'const r=await impRun(del,([c,id])=>db.doc(c+"/"+id).delete(),', 'const r=await impRun([],([c,id])=>db.doc(c+"/"+id).delete(),', 'deletes'),
 ('imp_replace', 'only the cards are deleted', 'for(const c of IMP_COLLS)for(const id of have[c])del.push([c,id]);', 'for(const c of ["entscheidungen"])for(const id of have[c])del.push([c,id]);', 'orders'),
 ('imp_replace', 'no progress while deleting', 'n=>say("löscht … "+n+" von "+del.length)', 'n=>{}', 'deleting'),
 ('imp_stop', 'a failed write does not stop the import', 'if(k>=0)return {done,err:r[k].reason,at:part[k]}', '', 'note'),
 ('imp_stop', 'the stop does not say how far it got', '". Bis dahin eingelesen: "+r.done+" von "+todo.length+" Dokumenten; der Rest fehlt im Buch."', '"."', 'note'),
 ('imp_stop', 'after a stop no second import can start', 'finally{importing=false;impAsk=null;arm()}', 'finally{impAsk=null}', 'again'),
 ('keys_scope', 'Cmd/Ctrl+Enter listens on the whole document instead of the field', 'ta.addEventListener("keydown",e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey))', 'document.addEventListener("keydown",e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey))', 'bodyCmdEnter'),
 ('lazy_cards', 'every card body is built, open or not', '  if(d.open)build();\n', '  build();\n', 'closedWithBody'),
 ('links_http', 'any address counts as a link', 'function httpUrl(u){u=String(u==null?"":u).trim();return /^https?:\\/\\/[^\\s\\/]/i.test(u)?u:""}', 'function httpUrl(u){return String(u==null?"":u)}', 'notHttp'),
 ('links_safe', "an order's text is set as HTML", 'el("span",{class:"atext"},linked(a.text||""))', '(()=>{const s=el("span",{class:"atext"});s.innerHTML=a.text||"";return s})()', 'orderMarkupElements'),
 ('live_slow_caps', 'the comments capability is awaited before the cards are read (the page as it is)', '  window.claude.use("comments").then(c=>{comments=c},()=>{comments=null});', '  try{comments=await window.claude.use("comments")}catch(e){comments=null}', 'msUntilLive'),
 ('local_times', 'talk and card times shown in UTC hours', '" "+p(d.getHours())+":"+p(d.getMinutes())}', '" "+p(d.getUTCHours())+":"+p(d.getMinutes())}', 'cardSteps'),
 ('look_back', 'the look back is asked before its release has come', 'return !!(a&&b&&b>=a)}', 'return true}', 'items'),
 ('md_dark', 'the table box is white in dark mode', 'border-radius:6px;background:var(--sheet);white-space:normal;overflow-wrap:normal}', 'border-radius:6px;background:#fff;white-space:normal;overflow-wrap:normal}', 'boxDark'),
 ('md_phone', 'the table box does not scroll, so the table widens the page', '.mdtw{max-width:100%;min-width:0;overflow-x:auto;', '.mdtw{', 'overflowing'),
 ('md_plain', 'a text without Markdown goes through the Markdown path too', 'if(!mdHas(s))return nl?document.createTextNode(s):linked(s);', '', 'stepHtml'),
 ('md_plain', 'a card section without Markdown is a box, not a paragraph', 'function mdBox(x){return mdHas(x)?', 'function mdBox(x){return true?', 'sectionParas'),
 ('md_safe', '`code` is set as HTML', 'into.append(el("code",{class:"mdc",text:m[1]}));', 'into.append((()=>{const c=el("code",{class:"mdc"});c.innerHTML=m[1];return c})());', 'foreignElements'),
 ('md_safe', 'a table cell is set as HTML', 'const cell=(tag,c,k)=>mdInline(c,el(tag,al[k]?{style:"text-align:"+al[k]}:{}),nl);', 'const cell=(tag,c,k)=>{const e=el(tag,{});e.innerHTML=c;return e};', 'foreignElements'),
 ('md_table', 'no table is built from a pipe table', 'if(mdTab(ls,i)){flush();', 'if(false&&mdTab(ls,i)){flush();', 'tables'),
 ('md_table', 'a "## " line stays a text line', 'if(h&&h[2]){flush();', 'if(false){flush();', 'heading'),
 ('md_table', '**…** becomes italic, not bold', 'const e=document.createElement(m[2]!=null?"strong":"em");', 'const e=document.createElement("em");', 'boldInTable'),
 ('md_table', 'the line of a closed step shows the Markdown marks', 'const head=mdFlat(m.text||"")', 'const head=String(m.text||"")', 'closedHead'),
 ('move_keeps_stand', 'the card\'s own "Ziel" dropdown moves a card in "Prüfen" (the owner\'s case)', '  {const why=moveBlock(r);if(why&&canWrite){zi.disabled=true;zi.title=why}}\n  zi.addEventListener("change",()=>{if(moveBlock(r)&&canWrite){zi.value=lz;return}', '  zi.addEventListener("change",()=>{', 'cardZiel'),
 ('move_keeps_stand', 'a change on a shut "Verschieben" still writes', 'if(moveBlock(r)||z===here){ms.value=here;return}', 'if(z===here){ms.value=here;return}', 'pruefenDoc'),
 ('move_keeps_stand', 'a move puts the card back to "entschieden" (as the owner saw it)', 'if(await save(r,{ziel:z},note)){r.ziel=z;render(true)}', 'if(await save(r,{ziel:z,blatt:"entschieden",status:"entschieden"},note)){r.ziel=z;render(true)}', 'moveWrite'),
 ('no_errors_idle', 'each card snapshot leaves an unhandled rejection', 'render();renderStats();setTimeout(runRules,0);', 'render();renderStats();setTimeout(runRules,0);Promise.reject(new Error("deliberate break"));', 'page error'),
 ('order_edit_live', '"Speichern" of an edited order does not go live to Claude', 'await liveSend(k,t,"save","[A:"+id+"] "+(t||"(Bild)"),null,$("#auftrag"));', '', 'saveFirst'),
 ('order_lease', '"in_bearbeitung" holds for ever, not 15 minutes', 'function aHeld(a){return !!a&&a.status==="in_bearbeitung"&&Date.now()-ts(a.bearbeitet_seit)<A_LEASE}', 'function aHeld(a){return !!a&&a.status==="in_bearbeitung"}', 'a1'),
 ('perf_700', 'every view switch wastes 900 ms', 'b.onclick=()=>{view=k;focusNr=null;', 'b.onclick=()=>{{const _t=performance.now();while(performance.now()-_t<900);}view=k;focusNr=null;', 'worstViewMs'),
 ('phone_390', 'the release bar gets a minimum width of 450 px', '.body,.alist,.steps{overflow-wrap:anywhere}', '.ready{min-width:450px}.body,.alist,.steps{overflow-wrap:anywhere}', 'overflowing'),
 ('phone_extern', 'no note beside "Senden" on a phone', 'function extNote(b){if(!PHONE||', 'function extNote(b){if(true||', 'note'),
 ('phone_tap', 'the phone sizes for buttons are gone', '@media (max-width:640px),(pointer:coarse){.act,.mv', '@media (max-width:1px){.act,.mv', 'small'),
 ('read_without_tokens', '"Gelesen" asks for the token numbers again when they are missing', 'if(true){const p=Object.assign({},patch);', 'if(!miss.length){const p=Object.assign({},patch);', 'asked'),
 ('ready_below', 'the counts table stands beside the release line again', 'box.append(el("div",{class:"rtabw"},tb));', 'box.append(tb);', 'below'),
 ('ready_counts', 'the current release stands last in the table', 'return zz===z?"0":k&&ck&&k>ck?', 'return zz===z?"9":k&&ck&&k>ck?', 'rows'),
 ('rec_match', 'cards without a recognizable option count too', 'if(a&&b){m++;if(a===b)n++}', '{m++;if(a===b)n++}', 'cell'),
 ('reconnect', 'an ended listener is not subscribed again', 'if(!end){const ms=Math.min(60000,2000*2**tries++)*(0.75+Math.random()/2);setTimeout(go,ms)}', '', 'afterRetry'),
 ('rel_chips', 'the chips come from every card not done again', 'const zs=[...new Set(keys.flatMap(k=>colRows(k)).map(', 'const zs=[...new Set(rows.filter(r=>r.blatt!=="erledigt").map(', 'claude'),
 ('rel_chips', '"Entschieden von" is not applied to the chips', 'keys.flatMap(k=>colRows(k))', 'keys.flatMap(k=>rows.filter(r=>r.blatt===k))', 'claudeOnly'),
 ('rel_chips', 'the chips are in alphabetical order', '.map(r=>String(r.ziel||"").trim()||"Ziel offen"))].sort(byZiel);', '.map(r=>String(r.ziel||"").trim()||"Ziel offen"))].sort();', 'claude'),
 ('rel_chips', 'a folded target is no longer offered', '.map(r=>String(r.ziel||"").trim()||"Ziel offen"))]', '.map(r=>String(r.ziel||"").trim()||"Ziel offen").filter(z=>!hiddenZ.has(z)))]', 'folded'),
 ('rel_chips', 'a tab without columns shows chips', 'const vw=VIEWS.find(x=>x[0]===view),keys=vw&&vw[2];if(!keys)return;', 'const vw=VIEWS.find(x=>x[0]===view),keys=vw&&vw[2]||["vorrat","entschieden","arbeit","offen","pruefen"];', 'releases'),
 ('rel_chips', 'the "Ziel" dropdown offers older releases again', '(z==="später"||z==="Buch"||k&&(!ck||k>=ck))', 'true', 'zielNew'),
 ('rel_chips', 'the "Ziel" dropdown drops the card\'s own old value', 'set.add("Buch");set.add("später");set.add("");if(cur)set.add(cur);', 'set.add("Buch");set.add("später");set.add("");', 'zielOld'),
 ('releases_columns', 'the releases table lays its columns out by content again', '.atab.rtab{table-layout:fixed}', '.atab.rtab{table-layout:auto}', 'afterGroup'),
 ('releases_fold', 'a shut release still shows its rows', '    if(rshut){tb.querySelector("thead").hidden=true;body.hidden=true}\n', '', 'shut'),
 ('releases_fold', 'the toggle of a release is not kept for the session', 'try{sessionStorage.setItem("eb-rrel",JSON.stringify([...relShut]))}catch(e){}', '', 'stored'),
 ('releases_groups', 'no group starts shut', 'GRP_SHUT=new Set(["erledigt","arbeit","pruefen","verworfen"])', 'GRP_SHUT=new Set([])', 'shutAtOpen'),
 ('releases_groups', 'the groups stand in the order of the Stand filter (Vorrat first)', 'const GRP_ORD=["offen","entschieden","arbeit","pruefen","erledigt","verworfen","vorrat"]', 'const GRP_ORD=["vorrat","offen","entschieden","arbeit","pruefen","erledigt","verworfen"]', 'groups'),
 ('releases_groups', 'a group row sums the estimate into "verbraucht"', 'si=sum(list,r=>parseTok(r.tokens_ist))', 'si=sum(list,r=>parseTok(r.tokens_prognose))', 'groups'),
 ('releases_groups', 'the rows are no longer sorted within their group', 'const mine=g.rows.filter(pass).sort(cmp);', 'const mine=g.rows.filter(pass);', 'sortedDown'),
 ('releases_groups', 'a toggle is not kept for the session', 'try{sessionStorage.setItem("eb-rgrp",JSON.stringify([...rgOpen]))}catch(e){}', '', 'storedToggle'),
 ('releases_layout', 'the releases table keeps the 980 px limit of "Erledigt"', '.archive.releases{max-width:none}', '', 'tableWidthShare'),
 ('releases_layout', 'the counts table\'s monospace reaches every ".rtab" again', '.rtabw .rtab td{font-family:var(--mono)', '.rtab td{font-family:var(--mono)', 'titleMono'),
 ('releases_layout', 'the headline is right-aligned like the numbers', '.atab.rtab td.t{width:100%;text-align:left;', '.atab.rtab td.t{width:100%;text-align:right;', 'titleAlign'),
 ('releases_move', 'a card in work or in "Prüfen" can be moved', '"schon erledigt":r.blatt==="arbeit"||r.blatt==="pruefen"?"wird schon bearbeitet"', '"schon erledigt":false?"wird schon bearbeitet"', 'arbeitDisabled'),
 ('releases_move', 'the move writes more than "ziel"', 'if(await save(r,{ziel:z},note)){r.ziel=z;render(true)}', 'if(await save(r,{ziel:z,blatt:"offen"},note)){r.ziel=z;render(true)}', 'write'),
 ('releases_move', 'no release beyond the highest one is offered', 'if(nx&&!choices.includes(nx))choices.push(nx);', '', 'choices'),
 ('releases_pct', "the column reads only Claude's value, not the rule from the Stand", 'text:(v=>v==null?"–":v+" %")(fertigPct(r))', 'text:(v=>v==null?"–":v+" %")(pctOf(r.fertig_pct))', 'cells'),
 ('releases_pct', 'the sums are plain averages even when every card has an estimate', 'wOf=x=>x[1]!=null&&x[1]>0?x[1]:fill;', 'wOf=x=>1;', 'sum28'),
 ('releases_pct', 'a card "In Umsetzung" without a value counts as 0 in the average', '.filter(x=>x[0]!=null);if(!k.length)return "–";', '.map(x=>[x[0]==null?0:x[0],x[1]]);if(!k.length)return "–";', 'groups'),
 ('releases_pct', 'the column has no fixed width of its own', 'pct:"c-pc w"', 'pct:"c-w w"', 'colClass'),
 ('releases_pct', 'the percentages stand left', 'el("td",{class:"w n pc",text:(v=>', 'el("td",{class:"w pc",text:(v=>', 'align'),
 ('releases_pct', '"fertig" does not sort', 'pct:r=>{const v=fertigPct(r);return v==null?-1:v},', '', 'sorted'),
 ('releases_phone', 'a card row spans the hidden token columns too, so the headline is squeezed', 'const span=RPHONE.matches?', 'const span=false?', 'titleWidthKept'),
 ('releases_phone', 'the estimated tokens stay on a phone', '["prog","Tokens geschätzt","w n"]', '["prog","Tokens geschätzt","n"]', 'hiddenCols'),
 ('releases_phone', 'the "fertig" column stays on a phone', '["pct","fertig","w n pc"]', '["pct","fertig","n pc"]', 'hiddenCols'),
 ('releases_table', 'the difference is taken the wrong way round (estimated minus used)', 'return a==null||b==null?null:b-a}', 'return a==null||b==null?null:a-b}', 'diffs'),
 ('releases_table', 'the next releases stand in reverse order', '.sort((a,b)=>relNum(a).localeCompare(relNum(b))),"später");', '.sort((a,b)=>relNum(b).localeCompare(relNum(a))),"später");', 'groups'),
 ('releases_table', 'a row opens its card on its own page, not below the row', '  const tog=()=>{open?set.delete(r.nr):set.add(r.nr);render(true)};', '  const tog=()=>gotoCard(r.nr);', 'expandedBelow'),
 ('reorder_lean', 'a reorder write stamps "geaendert" too', 'try{await db.doc("entscheidungen/"+r.nr).update({rang:v})}', 'try{await db.doc("entscheidungen/"+r.nr).update({rang:v,geaendert:new Date().toISOString()})}', 'geaendertMoved'),
 ('reorder_writes', 'one arrow rewrites every card of the lane (no run of cards is kept)', 'const kept=new Set();for(let q=n?end:-1;q>=0;q=prev[q])kept.add(q);', 'const kept=new Set();', 'writes'),
 ('roadmap_gone', 'the Art dropdown offers "Roadmap" again', '["ar","art","Art",ARTS.map(([v,t])=>[v,"Art "+t]),artOf],', '["ar","art","Art",[...ARTS.map(([v,t])=>[v,"Art "+t]),["Roadmap","Art Roadmap"]],artOf],', 'artOld'),
 ('roadmap_gone', 'the Typ dropdown is back', '  ["ar","art","Art",ARTS.map(', '  ["ty","typ","Typ",[["","Typ –"],["Aufgabe","Typ Aufgabe"],["Auftrag","Typ Auftrag"],["Thema","Typ Thema"]]],\n  ["ar","art","Art",ARTS.map(', 'typOld'),
 ('roadmap_gone', 'a card of typ "Roadmap" gets its badge again', '  // the "Roadmap" badge is gone with the public roadmap\n  metaLine.append(', '  if(/roadmap/i.test(r.typ||""))metaLine.append(el("span",{class:"badge roadmap",text:"Roadmap"}));metaLine.append(', 'badges'),
 ('rr_overview', 'targets without a card in the columns stay listed', 'rows.filter(r=>!isTopArt(r)&&cols.some(c=>c.key===r.blatt)).map(zOf)', 'rows.filter(r=>!isTopArt(r)).map(zOf)', 'rowsShown'),
 ('rr_overview', 'the targets stand in alphabetical order', '.map(zOf))].sort(byZiel);', '.map(zOf))].sort((a,b)=>a.localeCompare(b));', 'rowsShown'),
 ('rr_overview', '"später" stands before the next releases', 'zz==="später"?"2":zz==="Buch"?"3"', 'zz==="später"?"05":zz==="Buch"?"3"', 'rowsShown'),
 ('rr_overview', 'a Hinweis counts in the overview', 'rows.filter(r=>!isTopArt(r)&&cols.some(', 'rows.filter(r=>cols.some(', 'rowsShown'),
 ('rr_pct', 'one card without an estimate makes the sum a plain average again', 'wOf=x=>x[1]!=null&&x[1]>0?x[1]:fill;', 'wOf=x=>kn.length===k.length?x[1]:1;', 'sumB28'),
 ('rr_pct', '99.6 % rounds to "100 %"', 'return Math.min(v<100?99:100,Math.max(v>0?1:0,Math.round(v)))+" %"}', 'return Math.round(v)+" %"}', 'sumB29'),
 ('rr_pct', 'the column heads are as they were before (they break inside a word: "verbrauch / t")', '.atab.rtab th button{overflow-wrap:normal;word-break:normal;hyphens:manual;padding:6px 3px;font-size:12.5px}', '', 'brokenWords'),
 ('rr_pct', 'the column heads are wider than their columns', 'hyphens:manual;padding:6px 3px;font-size:12.5px}', 'hyphens:manual;padding:6px 3px;font-size:16px}', 'overflowHeads'),
 ('rr_phone', 'the runs box is 450 px wide', '.relruns{margin:6px 0 0;', '.relruns{margin:6px 0 0;min-width:450px;', 'overflowing'),
 ('rr_phone', 'a long run name does not wrap', 'display:flex;flex-direction:column;gap:2px;overflow-wrap:anywhere}', 'display:flex;flex-direction:column;gap:2px}', 'overflowing'),
 ('rr_phone', 'the "Live" links are 420 px wide', '.runlive,.steplive{font-weight:600;white-space:nowrap}', '.runlive,.steplive{font-weight:600;white-space:nowrap;display:inline-block;min-width:420px}', 'overflowing'),
 ('rr_runs', 'the runs are not shown in "Releases"', 'sec.append(tb);if(g.z===cur){const rb=runsBox();if(rb)sec.append(rb)}wrap.append(sec)}', 'sec.append(tb);wrap.append(sec)}', 'inReleases'),
 ('rr_runs', 'the runs stand under another release than the current one', 'if(g.z===cur){const rb=runsBox();', 'if(g.z!==cur){const rb=runsBox();', 'inReleases'),
 ('rr_runs', 'the runs stay in "Aufträge" too', '  // the running GitHub runs stand in "Releases", under the sum of the current release (runsBox)\n', '  {const rb=runsBox();if(rb)w.append(rb)}\n', 'runsInAuftraege'),
 ('rr_runs', 'a run counts on the button "Aufträge" again', 'k==="sitzung"?"":', 'k==="sitzung"?(runsLive().length?"⟳"+runsLive().length:""):', 'badge'),
 ('rr_runs', 'a finished run is shown too', 'function runsBox(){const live=runsLive();', 'function runsBox(){const live=laeufe;', 'runNames'),
 ('rr_runs', 'the link of a run is not called "Live"', 'class:"runlive",text:"Live"', 'class:"runlive",text:"Lauf ↗"', 'links'),
 ('rr_runs', 'a run address that is no http(s) still makes a link', 'function runUrl(x){return httpUrl(x&&x.url)||ghActions()}', 'function runUrl(x){return String(x&&x.url||"")||ghActions()}', 'links'),
 ('rr_runs', 'the page\'s default step still says "Baurechner"', '"GitHub-Prüflauf – alle Prüfungen grün"', '"Baurechner – alle Prüfungen grün"', 'stepText'),
 ('rr_runs', 'no "Live" link beside the step line', 'const l=stepRunLine("step-live");if(l)box.append(l)', 'const l=null;if(l)box.append(l)', 'stepLive'),
 ('rr_runs', 'a change of meta/laeufe does not redraw "Releases"', 'renderViews();renderReady();if(view==="releases")render()});', 'renderViews();renderReady()});', 'afterDone'),
 ('rr_steprun', 'the head has no line "GitHub-Prüflauf: …"', 'const l=stepRunLine("step-live");if(l)box.append(l)', 'const l=null;if(l)box.append(l)', 'head'),
 ('rr_steprun', 'the running step in the list has no run line', 's.z==="läuft"?stepRunLine():null,', 'null,', 'inList'),
 ('rr_steprun', 'the line names the run without a link', 'x=l.find(y=>runUrl(y))||l[0]', 'x=l[0]', 'head'),
 ('rr_steprun', 'the line stays after the run is done', 'function stepRunLine(id){const l=runsLive(),', 'function stepRunLine(id){const l=laeufe,', 'afterDone'),
 ('rr_steprun', 'the run line is 420 px wide', '.steprun{font-size:13px;margin-left:6px;overflow-wrap:anywhere}', '.steprun{display:inline-block;min-width:420px;font-size:13px;margin-left:6px}', 'wide'),
 ('rr_steprun', 'no "Live" link when the step shown does not run', 'else{const x=runsLive()[0],u=x&&runUrl(x);if(u)box.append(', 'else{const x=null,u=x&&runUrl(x);if(u)box.append(', 'bare'),
 ('rules_busy', 'the rules ignore the lease another tab holds', 'if(!await ruleTab())return;', '', 'writesWhileBusy'),
 ('rules_deferred', 'the rules start inside the snapshot callback', 'render();renderStats();setTimeout(runRules,0);', 'render();renderStats();runRules();', 'callsInsideSnapshot'),
 ('search_open', 'the found card obeys the release filter and the collapsed lanes', 'if(r){const d=card(r,[r]);', 'if(r&&visible(r)&&!laneShut(r.ziel)){const d=card(r,[r]);', 'shown'),
 ('send_once_after_fail', 'a retry after a failed write sends the comment to Claude again', 'const mem=liveMem(k,text,tag);if(mem)return {live:true,thread:mem.thread||null,why:""};', 'const mem=null;', 'cardSends'),
 ('settings_absent', 'a GitHub repository is built into the page as a default', 'function ghActions(){const r=String(S("github_repo","")).trim();', 'function ghActions(){const r=String(S("github_repo","beispiel/fest")).trim();', 'links'),
 ('settings_backup', 'the backup leaves the meta documents out', '"gespraech","statistik","meta","archiv"]){', '"gespraech","statistik","archiv"]){', 'collections'),
 ('settings_backup', 'the cycle is written again when it did not change', 'sel.addEventListener("change",async()=>{if(sel.value===last)return;', 'sel.addEventListener("change",async()=>{', 'writes'),
 ('settings_backup', '"⚙ Einstellungen" opens the change log', '$("#setbtn").addEventListener("click",showSettings);', '$("#setbtn").addEventListener("click",showLog);', 'dialog'),
 ('settings_present', "the owner's name from the settings is not taken over", 'OWNER=S("eigner","Eigner");TOKEN_RULE_AB', 'OWNER="Eigner";TOKEN_RULE_AB', 'filter'),
 ('stand_field', 'the Stand dropdown writes "status" again, not "blatt"', 'const p={blatt:v};if(v==="erledigt")', 'const p={status:v};if(v==="erledigt")', 'toEntschieden'),
 ('stand_field', 'the Status dropdown is back', 'const fields=el("div",{class:"row fields"},sel,zi,', 'const fields=el("div",{class:"row fields"},el("select",{id:"st-"+r.nr,"aria-label":"Status"}),sel,zi,', 'statusSelects'),
 ('stand_field', 'a change to "Prüfen" or "Erledigt" skips the buttons\' path (no token mark, no erledigt_am)', 'const p={blatt:v};if(v==="erledigt")p.erledigt_am=stampNow();\n    const ok=v==="erledigt"||v==="pruefen"?await moveTo(p):await save(r,p,note);', 'const p={blatt:v};\n    const ok=await save(r,p,note);', 'toPruefen'),
 ('stand_field', 'the chip shows the old "status" again', 'el("span",{class:"nr"},artLbl,r.nr),chip(r.blatt)),', 'el("span",{class:"nr"},artLbl,r.nr),chip(r.status)),', 'statusWordShown'),
 ('start_commit', 'a start without commit and green run goes out on the first click', 'if(!ok&&startSure!==z){startSure=z;', 'if(false){', 'writesAfterFirstClick'),
 ('startup_parallel', 'the page waits for the assets capability before the cards', '  pasteImages($("#auftrag-text"),"auftrag",$("#auftrag-bilder"),$("#auftrag-note"));', '  await window.claude.use("assets");pasteImages($("#auftrag-text"),"auftrag",$("#auftrag-bilder"),$("#auftrag-note"));', 'msUntilLive'),
 ('stat_sum', 'no row "Gesamt"', 'if(sum){const tx=sum(rs)', 'if(false){const tx=sum(rs)', 'sum'),
 ('stat_sum', 'the sum ignores the filters', 'if(sum){const tx=sum(rs)', 'if(sum){const tx=sum(list)', 'filtered'),
 ('stat_sum', 'the sum row goes below the releases', 'tx[i]})));tb.append(tr)}', 'tx[i]})));queueMicrotask(()=>tb.append(tr))}', 'sum'),
 ('stat_sum', 'a filter nothing passes hides the sum row', 'if(sum){const tx=sum(rs)', 'if(sum&&rs.length){const tx=sum(rs)', 'none'),
 ('stat_sum', 'Codezeilen are added up instead of the newest', 'fmtN(newest?newest.codezeilen:null)', 'fmtN(nums(r=>r.codezeilen))', 'sum'),
 ('stat_sum', 'no percentage beside "x von y"', 'x.n+" von "+x.m+" ("+Math.round(100*x.n/x.m)+" %)"', 'x.n+" von "+x.m', 'b27'),
 ('stat_sum', 'the old column name "Tokens (alle Sitzungen)"', '["Tokens gesamt",1,', '["Tokens (alle Sitzungen)",1,', 'heads'),
 ('stat_sum', 'the explanation keeps the old token text', 'Tokens gesamt: alles, was zwischen zwei Veröffentlichungen verarbeitet wurde', 'Tokens (alle Sitzungen): alles, was zwischen zwei Veröffentlichungen verarbeitet wurde', 'hintTokens'),
 ('talk_fold', 'the fold of a talk is not stored', 'tg.onclick=()=>{if(shut)gFold.delete(g.id);else gFold.add(g.id);try{localStorage.setItem("eb-gfold",JSON.stringify([...gFold]))}catch(e){}renderGespraech()};', 'tg.onclick=()=>{if(shut)gFold.delete(g.id);else gFold.add(g.id);renderGespraech()};', 'stored'),
 ('talk_order', 'open talks sorted by their start, not their newest message', '.sort((a,b)=>lastT(b).localeCompare(lastT(a)))', '.sort(by)', 'order'),
 ('talk_send', 'the send button is neither guarded nor greyed while sending', 'if(b._busy)return;b._busy=true;b.disabled=true;', 'b._busy=true;', 'disabledDuringSend'),
 ('talk_send_fail', 'a failed talk send no longer puts the text back', 'catch(e){if(!ta.value){ta.value=sent;dSet("t:g:"+g.id,sent)}note.textContent=', 'catch(e){note.textContent=', 'fieldAfterFailure'),
 ('upd_current', 'a current book is migrated anyway', 'if(c===0){UPD.busy=false;', 'if(c===0&&false){UPD.busy=false;', 'writes'),
 ('upd_current', "the owner's rules never start on a current book", 'if(c===0){UPD.busy=false;', 'if(c===0){', 'rule'),
 ('upd_fail_stops', 'a failed migration does not stop the run', 'beim nächsten Öffnen wird es noch einmal versucht.","fail");return}}', 'beim nächsten Öffnen wird es noch einmal versucht.","fail")}}', 'card'),
 ('upd_fail_stops', 'the migrations run in list order, not by version', '.sort((a,b)=>updVerCmp(a.to,b.to))', '', 'ran'),
 ('upd_fail_stops', 'a recorded migration runs again', '    if(done.includes(m.to))continue;\n', '', 'ranAgain'),
 ('upd_fail_stops', 'the version moves with every migration that ran', 'UPD.done.push({to:m.to,r:r==null?"":String(r)});await write()', 'UPD.done.push({to:m.to,r:r==null?"":String(r)});await write({version:m.to})', 'version'),
 ('upd_fail_stops', 'the failure does not name the migration', '"Aktualisierung angehalten bei "+m.to+": "', '"Aktualisierung angehalten: "', 'barFail'),
 ('upd_fail_stops', "the owner's rules write while the update is not done", 'async function runRules(){if(UPD.busy||', 'async function runRules(){if(', 'ruleHeld'),
 ('upd_version_only', 'the recorded migrations are forgotten', 'const done=Array.isArray(cur.migriert)?cur.migriert.slice():[];', 'const done=[];', 'migriert'),
 ('upd_version_only', 'the version stays when there is nothing to migrate', 'try{await write({version:PAGE_VERSION,', 'try{await write({', 'version'),
 ('upd_version_only', 'the page does not say that the book was brought up to date', 'updBar("Buch aktualisiert: Datenstand "', 'void("Buch aktualisiert: Datenstand "', 'bar'),
 ('upd_version_only', "the owner's rules stay off after the update", 'UPD.busy=false;UPD.book=PAGE_VERSION;', 'UPD.book=PAGE_VERSION;', 'rule'),
 ('upd_migrate_old', 'the old stamp is not copied to eigner_am', 'db.doc("entscheidungen/"+c.id).update({eigner_am:take(c.d)})', 'Promise.resolve()', 'e1'),
 ('upd_migrate_old', 'a newer eigner_am is written over', 'return o&&(!n||String(o)>String(n))?o:null', 'return o?o:null', 'e2'),
 ('upd_migrate_old', 'the migration is not idempotent (an equal stamp is written again)', 'String(o)>String(n))?o:null', 'String(o)>=String(n))?o:null', 'writesAgain'),
 ('upd_migrate_old', 'the archived cards are left out', 'for(const a of arch){let ch=false;', 'for(const a of []){let ch=false;', 'arch'),
 ('upd_migrate_old', 'the owner name from the settings is not used', 'if(n&&seen.has(n+"_am"))old=n+"_am"', 'if(false)old=n+"_am"', 'version'),
 ('upd_migrate_old', 'meta/buch.version is not set', 'await write({version:PAGE_VERSION,aktualisiert:new Date().toISOString()})', 'await write({aktualisiert:new Date().toISOString()})', 'version'),
 ('upd_migrate_old', 'the migration does not record itself', 'done.push(m.to);UPD.done.push(', 'UPD.done.push(', 'migriert'),
 ('upd_migrate_old', 'no step shown while it runs', '    updBar("Aktualisiere das Buch von "+shown+" auf "+PAGE_VERSION+" … "+step,"run");\n', '', 'barRun'),
 ('upd_migrate_old', 'no count of the cards while it runs', 'say(Math.min(i+10,todo.length)+" von "+todo.length+" Karten")', '0', 'barCards'),
 ('upd_migrate_old', 'no word when it is done', 'updBar("Buch aktualisiert: Datenstand "', 'void("Buch aktualisiert: Datenstand "', 'barOk'),
 ('upd_migrate_old', 'the migration stamps "geaendert" on the cards', 'update({eigner_am:take(c.d)})', 'update({eigner_am:take(c.d),geaendert:new Date().toISOString()})', 'cardWritesStamp'),
 ('upd_migrate_old', "the owner's rules stay off after the update", 'UPD.busy=false;UPD.book=PAGE_VERSION;', 'UPD.book=PAGE_VERSION;', 'busy'),
 ('upd_newer', 'an older page writes its version over a newer book', 'if(c>0){updBar(', 'if(false){updBar(', 'writes'),
 ('upd_newer', 'an older page says nothing', 'if(c>0){updBar("Das Buch hat', 'if(c>0){void("Das Buch hat', 'bar'),
 ('upd_old_scan', 'of several unknown fields the first is taken', 'if(seen.size>1)throw new Error(', 'if(false)throw new Error(', 'two'),
 ('upd_old_scan', 'meta/buch.stempel_alt is ignored', 'let old=typeof bk.stempel_alt==="string"?bk.stempel_alt.trim():"";', 'let old="";', 'hand'),
 ('upd_old_scan', 'a single unknown field is not taken', 'old=[...seen][0]||""', 'old=""', 'alone'),
 ('upd_old_scan', 'a failed card write goes unnoticed', 'if(k>=0)throw new Error("Karte "+part[k].id+": "+errWord(r[k].reason));', '', 'cardFail'),
 ('upd_readonly', 'a reader migrates the book', 'if(!can){updBar(', 'if(false){updBar(', 'writes'),
 ('upd_readonly', 'a reader gets no hint', 'if(!can){updBar("Dieses Buch', 'if(!can){void("Dieses Buch', 'bar'),
 ('upd_readonly', 'the bar stands at the end of the page, not under the header', 'if(h)h.after(b);else', 'if(h)document.body.append(b);else', 'barAfterHeader'),
 ('utc_times', "an order's time is shown as stored (UTC), not in local time", 'const time=el("time",{text:tl(a.zeit)});', 'const time=el("time",{text:String(a.zeit||"").replace("T"," ").slice(0,16)});', 'orderTimeShown'),
 ('verworfen_group', '"Verworfen" under "Erledigt" starts open', 'const verwBox=()=>{const shut=!verwOpen,', 'const verwBox=()=>{const shut=false,', 'toggle'),
 ('verworfen_group', 'the rejected cards are not listed under "Erledigt"', '  if(gone.length)wrap.append(verwBox());\n  board.append(wrap);', '  board.append(wrap);', 'toggle'),
 ('verworfen_group', 'the toggle of "Verworfen" is not kept for the session', 'try{sessionStorage.setItem("eb-verw",verwOpen?"1":"")}catch(e){}', '', 'stored'),
 ('verworfen_group', 'the "Verworfen" group of "Releases" starts open', 'GRP_SHUT=new Set(["erledigt","arbeit","pruefen","verworfen"])', 'GRP_SHUT=new Set(["erledigt","arbeit","pruefen"])', 'groups'),
 ('verworfen_group', 'a rejected card can be moved', 'r.blatt==="verworfen"?"verworfen":', '', 'move'),
 ('waits_agree', 'the badge also counts "wartet: Dich" cards that "Für Dich" does not show', 'const mineRows=forYou().all,cards=mineRows.length;', 'const mineRows=[...forYou().all,...rows.filter(r=>r.wartet==="Dich"&&r.blatt!=="erledigt"&&!forYou().all.includes(r))],cards=mineRows.length;', 'badgeN'),
 ('waits_count', 'read talks count as waiting too', 'const talks=gsp.filter(g=>g.status!=="gelesen"&&', 'const talks=gsp.filter(g=>', 'text'),
 ('waits_count', 'one card or answer reads in the plural', 'text:k+" "+(k===1?one:many)', 'text:k+" "+many', 'textOneEach'),
 ('waits_count', 'the answers part leads to "Für Dich" instead of "Aufträge"', '"Antworten","sitzung","wa"', '"Antworten","dich","wa"', 'viewAfterAnswers'),
 # "Archiv packen" in the settings
 ('pack_list', 'a release with an open card is offered for packing', 'if(!relOrd(z)||i>last||!relClosed(z))return;', 'if(!relOrd(z)||i>last)return;', 'lines'),
 ('pack_list', 'a release with nothing to pack is listed', 'if(x.packed||!(x.k.length+x.a.length+x.g.length))continue;', 'if(x.packed)continue;', 'lines'),
 ('pack_list', 'a packed release is listed', 'if(x.packed||!(x.k.length+x.a.length+x.g.length))continue;', 'if(!(x.k.length+x.a.length+x.g.length))continue;', 'lines'),
 ('pack_list', 'a packed release is offered again', 'packed:!!(s.archiv&&typeof s.archiv==="object")', 'packed:false', 'lines'),
 ('pack_list', 'the section does not say that "Buch", "später" and no target are never packed', ' Karten mit Ziel „Buch“, „später“ oder ohne Ziel werden nie gepackt.', '', 'hint'),
 ('pack_list', 'orders not taken and talks not read are packed too', 'a=ia.filter(x=>x.status!=="neu"&&x.status!=="in_bearbeitung"),g=ig.filter(x=>x.status==="gelesen")', 'a=ia,g=ig', 'lines'),
 ('pack_happy', '"Packen" writes at the first tap, without the question', 'b.onclick=()=>{for(const q of list.querySelectorAll("#pack-frage"))q.remove();', 'b.onclick=()=>{packRun(x.z,say);return;for(const q of list.querySelectorAll("#pack-frage"))q.remove();', 'writesAfterFirst'),
 ('pack_happy', 'the archive docs are not read back', 'for(const d of docs){said("prüft das Archiv', 'for(const d of []){said("prüft das Archiv', 'calls'),
 ('pack_happy', 'statistik is written after the deletes', 'await db.doc("statistik/"+(sd?sd.id:z)).update(packSums(ek,ea,eg,docs));', 'setTimeout(()=>db.doc("statistik/"+(sd?sd.id:z)).update(packSums(ek,ea,eg,docs)),500);', 'calls'),
 ('pack_happy', 'statistik is written over instead of updated (its other fields are lost)', '.update(packSums(ek,ea,eg,docs))', '.set(packSums(ek,ea,eg,docs))', 'stat.ordnung'),
 ('pack_happy', 'an order in the archive has no "release"', 'ea=p.a.map(x=>Object.assign({},x,{release:z}))', 'ea=p.a', 'aSame'),
 ('pack_happy', 'the token difference counts cards with only one of the two numbers', 'if(p!=null&&i!=null){diff+=i-p;has.d++}', '{diff+=(i||0)-(p||0);has.d++}', 'stat.tokens_diff'),
 ('pack_happy', '"Ja, packen" asks with a browser dialog', 'yes.onclick=()=>{ask.remove();', 'yes.onclick=()=>{if(!confirm("Packen?"))return;ask.remove();', 'dialogs'),
 ('pack_happy', 'the deletes show no progress', 'said("löscht die Originale … "+(n+1)+" von "+del.length);', '', 'progress'),
 ('pack_readback', 'the read-back compares only the number of entries', 'if(!bad)for(let i=0;i<got.length;i++)if(canon(got[i])!==canon(want[i]))', 'if(false)for(let i=0;i<got.length;i++)if(canon(got[i])!==canon(want[i]))', 'deletes'),
 ('pack_delete_fail', 'a failed delete does not stop the others', 'catch(x){return said("Gestoppt beim Löschen von "', 'catch(x){said("Gestoppt beim Löschen von "', 'deletes'),
 ('pack_changed', 'an original changed since packing is deleted all the same', 'if(live&&canon(without(live,key))!==canon(without(e,"id")))return', 'if(false)return', 'note'),
 ('pack_split', 'the cards are not split at 200 KB', 'if(cur.length&&size+l>PACK_MAX)flush();', '', 'docs'),
 ('pack_ro', 'the section is shown without write access', 'function packSection(box){if(!db||!canWrite)return;', 'function packSection(box){if(!db)return;', 'section'),
 ('pack_phone', 'the list is 480 px wide', '.packlist{list-style:none;', '.packlist{min-width:480px;list-style:none;', 'overflowing'),
 # the one order of releases, and "Karten und Tokens" counted live
 ('stat_order', 'the releases are sorted by "ordnung" again', 'stat=sortStat(s.docs.map(d=>Object.assign({id:d.id},d.data())));', 'stat=s.docs.map(d=>Object.assign({id:d.id},d.data())).sort((a,b)=>(a.ordnung??0)-(b.ordnung??0));', 'order'),
 ('stat_order', '"-beta" is not read as a version', '(?:(-?beta|b)(\\d*))?$/i', '(?:(b)(\\d*))?$/i', 'order'),
 ('stat_order', 'a release without "veroeffentlicht" goes to the top', 'v=-Infinity;for(const p of pub)', 'v=Infinity;for(const p of [])', 'order'),
 ('stat_order', 'the newest Codezeilen are taken by "ordnung"', 'const newest=sortStat([...rs]).reverse().find(', 'const newest=[...rs].sort((a,b)=>(b.ordnung??0)-(a.ordnung??0)).find(', 'codeSum'),
 ('stat_order', 'the span of a release starts at the first release, not the previous one', 'for(let j=i-1;j>=0;j--){const t=relPub(stat[j]);', 'for(let j=0;j<i;j++){const t=relPub(stat[j]);', 'pack'),
 ('stat_live', 'a release not packed is not counted from the cards', 'if(!live.length)return r;const L=', 'if(true)return r;const L=', '3_0_0b28'),
 ('stat_live', 'live rows are not marked', 'r._live?{class:"livesum",title:"aus den Karten im Buch gezählt"}:{}', '{}', '3_0_0b28'),
 ('stat_live', 'a packed release ignores the cards in the book again', '  return Object.assign({},r,{karten:N(r.karten)+L.karten,', '  return r;return Object.assign({},r,{karten:N(r.karten)+L.karten,', '3_0_0b26'),
 ('stat_live', 'the explanation still says "–" before packing', 'Ein gepacktes Release zeigt die Summen vom Packen ins Archiv; alle anderen werden aus den Karten im Buch gezählt (kursiv). Ein Release ohne Karten zeigt „–“.', 'Vor dem Packen steht hier „–“.', 'hint'),
 ('stat_live', 'live rows are not italic', '.livesum td{font-style:italic}', '', 'italic'),
 # the "Ziel" dropdown and the target "Buch"
 ('ziel_buch', '"Buch" is offered although no card carries it', 'if(rows.some(r=>r.ziel==="Buch"))set.add("Buch");', 'set.add("Buch");', 'without'),
 ('ziel_buch', '"Buch" is never offered', 'if(rows.some(r=>r.ziel==="Buch"))set.add("Buch");', '', 'with'),
]
def run(page_text, tag, name):
    p = os.path.join(here, tag + '.html'); open(p, 'w', encoding='utf-8').write(page_text)
    env = dict(os.environ, ONLY='^%s$' % name, OUT=os.path.join(here, 'out_' + tag), FORBIDDEN='0', JOBS='1')
    r = subprocess.run([os.path.join(suite, 'run_all.sh'), p], env=env, capture_output=True, text=True)
    return next((l for l in r.stdout.splitlines() if l.split(' ')[1:2] in ([name], [name + ':'])), r.stdout.strip() or r.stderr.strip())
names = sorted(x[:-12] for x in os.listdir(os.path.join(suite, 'scenarios')) if x.endswith('.expect.json'))
missing = set(names) - {b[0] for b in B}
if missing: sys.exit('no break for: %s' % ', '.join(sorted(missing)))
B = [b for b in B if b[0] in names]
def one(i):
    name, what, old, new, field = B[i]
    try: after = run(once(base, old, new), 'brk_%03d' % i, name)
    except Stale as e: after = 'STALE ' + str(e)
    return after
# one Chrome pool (lib/pool.py) for every run_all.sh call below: JOBS Chromes for the whole counter-proof, not one per call
jobs = int(os.environ.get('JOBS', '6'))
pdir = tempfile.mkdtemp(prefix='eb_pool_')
os.environ['CHROME_POOL'] = sock = os.path.join(pdir, 'pool.sock')
pool = subprocess.Popen([sys.executable, os.path.join(suite, 'lib', 'pool.py'), 'serve', sock, str(jobs)])
try:
    for _ in range(300):
        if os.path.exists(sock) or pool.poll() is not None: break
        time.sleep(0.1)
    if not os.path.exists(sock): sys.exit('no Chrome pool (lib/pool.py) came up')
    with ThreadPoolExecutor(jobs) as ex:
        before = dict(zip(names, ex.map(lambda n: run(base, 'pre_' + n, n), names)))
        afters = list(ex.map(one, range(len(B))))
finally:
    pool.terminate()
    try: pool.wait(30)
    except subprocess.TimeoutExpired: pool.kill(); pool.wait()
    shutil.rmtree(pdir, ignore_errors=True)
rows = []; bad = 0
for (name, what, old, new, field), after in zip(B, afters):
    good = before[name].startswith('ok ') and after.startswith('FAIL ') and field in after
    bad += not good
    rows.append((name, what, before[name], after, good))
    print(('proven ' if good else 'NOT PROVEN ') + name + ' | ' + what + ' | ' + after[:160] + ('' if good else ' || before: ' + before[name][:300]))
for d in os.listdir(here):
    if d.endswith('.html'): os.remove(os.path.join(here, d))
    if d.startswith('out_'): subprocess.run(['rm', '-rf', os.path.join(here, d)])
md = ['# Counter-proof of the decision book suite', '',
      'Made by `breaks/counterproof.py` on page %s. For every break one small change in a scratch copy; the scenario '
      'is run alone and must print FAIL naming the field the break is about, and it must be ok on the unbroken page. '
      'The scratch copies are deleted afterwards.' % ver, '',
      '| scenario | break | ok before the break | FAIL line after the break |', '|---|---|---|---|']
esc = lambda s: s.replace('|', '\\|')
for name, what, b4, after, good in rows:
    md.append('| %s | %s | %s | `%s` |' % (name, esc(what), 'yes' if b4.startswith('ok ') else esc(b4[:80]), esc(after[:400])))
md += ['', '%d of %d breaks proven, %d scenarios.' % (len(rows) - bad, len(rows), len(names))]
open(os.path.join(suite, 'COUNTERPROOF.md'), 'w', encoding='utf-8').write('\n'.join(md) + '\n')
print('%d of %d proven' % (len(rows) - bad, len(rows))); sys.exit(1 if bad else 0)
